spring:
  config:
    import: optional:file:.env[.properties]
server:
  servlet:
    context-path: "/api"
app:
  azure-secret: ${BING_SEARCH_KEY}
logging:
  level:
    io.temporal.internal.activity.ActivityTaskExecutors: ERROR
